const mongoose = require('mongoose');

var PlanModel = new mongoose.Schema({
    socialSecurityEarnings: Number,
    socialSecurityAge62Earnings: Number,
    socialSecurityAge70Earnings: Number,
    firstName: String, 
    spouse: String,
    spousesFullName: String,
    workAmount: String, 
    retirementAge: Number,
    retirementIncome: Number,
    dateOfBirthDay: Number, String,
    dateOfBirthYear: Number, String, 
    dateOfBirthMonth: String, 
    maritalStatus: String, 
    kids: String,
    numberOfKids: Number,
    business: String, Number, Boolean,
    businessMoneyNeeded: Number, 
    care: String,
    charity: String,
    majorPurchases: String,
    purchasesCost: Number,
    support: String,
    supportCost: Number,
    health: String,
    collegeSpendingAmount: Number,
    college: String, 
    currentEarnings: Number,
    currentSavings: Number,
    assetValue: Number,
    increaseIncome: String,
    increaseIncomeAmount: Number,
    outOfWork: String,
    lifeInsurance: String,
    taxPlan: String,
    riskAttitude: String,
    volatility: String, 
    changePortfolio: String,
    portfolioTradeoff: String,
    investments: String,
    investmentsAmount: String, Number,
    realEstate: String,
    realEstateAmount: String, Number,
    alternativeAssets: String, 
    alternativeAssetsAmount: String, Number,
    otherAssets: String,
    otherAssetsAmount: String, Number,
    powerOfAttorney: String,
    will: String,
    medicare: String,
    pension: String,
    pensionEarnings: String, Number,
    pensionTimeframe: String, Number,
    pensionInflation: String, Number, Boolean, 
    socialSecurity: String,
    mortgage: String,
    mortgageAmount: String,
    creditCardDebt: String,
    creditCardDebtAmount: String, Number,
    medicalDebt: String,
    medicalDebtAmount: String, Number,
    carFinancing: String,
    carFinancingAmount: String, Number,
    studentLoans: String,
    studentLoanAmount: String, Number,
    additionalDebt: String,
    additionalDebtAmount: String, Number,
    lifeInsuranceDocument: Buffer, 
    totalFutureSpending: Number, String,
    rateOfReturn: Number,
    lengthOfRetirement: Number,
    totalHealthcareCosts: Number, 
    currentAge: Number,
    yearsUntilRetirement: Number,
    savingsByRetirement: Number,
    projectedRetirementIncome: Number,
    financialHealthScore: String,
    lengthOfPension: Number,
    savingsDecision: String, Number,
    socialSecurityDecision: String, Number,
    investmentProfileDecision: String, Number,
    retirementIncomeDecision: String, Number,
    projectedRetirementIncomeAfterSsDecision: String, Number,
});

module.exports = mongoose.models.Plan || mongoose.model("Plan", PlanModel);